config/routes.rb
Rails.application.routes.draw do
  resources :countries
  root 'countries#index'

end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    @countries = Country.all
  end

  def new
    @country = Country.new
  end

  def create
    Country.create(country_params)
    redirect_to( countries_path )
  end

  def show
    @country = Country.find(params[:id])
  end

  def destroy
    country = Country.find(params[:id])
    country.destroy
    redirect_to( countries_path )
  end

  def edit
    @country = Country.find(params[:id])
  end

private

def country_params
  params.require(:country).permit(:name, :population, :image, :stereotype_image)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/countries/index.html.erb
<% @countries.each do |country| %>
<%= country.name %>'s population is <%= country.population %>
<%= link_to("Show #{country.name}", country_path(country)) %>
<%= button_to('Destroy Country (listing, not the actual place)', country_path(country), method: :delete, data: {confirm: 'Destroy them? Are you sure?!'}) %>
<%= link_to('Edit Country', edit_country_path(country)) %>
<br>
<% end %>

app/views/countries/new.html.erb
<%= form_for @country do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :population %>
<%= f.text_field :population %>
<br>
<%= f.label :image %>
<%= f.text_field :image %>
<br>
<%= f.label :stereotype_image %>
<%= f.text_field :stereotype_image %>
<br>
<%= f.submit 'Create country!' %>
<% end %>

app/views/countries/show.html.erb
<h1> <%= @country.name %> </h1>
<p> <%= @country.name %>'s population is <%= @country.population %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FactbookApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav> 
<ul>
<li> <%= link_to('Countries', countries_path) %></li>
<li> <%= link_to('New Country', new_country_path) %> </li>
</ul>
</nav>

<%= yield %>

</body>
</html>